### ISSUE TITLE
How to Publish JSON payloads

### ISSUE THREAD

**Issue by rgbkrk** [alexarchambault/jupyter-kernel#11]
nteract can publish direct JSON payloads for some mimetypes (instead of having to include HTML payloads).

Vega lite for instance, as in https://github.com/nteract/nteract/pull/1113, can be published as `application/vnd.vegalite+json`. The resulting payload is direct JSON for the `display_data` and `execute_result` data fields, resulting in something that is not double encoded and more accessible for indexing. The signature on `publish.display` is `(String, String)*`. How could I publish String -> SomeJSONType?

**Comment by alexarchambault** [comment]
It can't be done out-of-the-box for now. A quick workaround could be to add a method that would parse the values as JSON, before sending them to the client, as there's no standard JSON AST for Scala... (the [one from json4s](https://github.com/json4s/json4s-ast) isn't really widely adopted). It might also be possible to have a method injecting it directly in the response, although that's a bit risky.

Also, [upickle](https://github.com/lihaoyi/upickle-pprint) lands in the user classpath from jupyter-scala sessions, via Ammonite. So maybe `api` could depend on it here, or the kernel could add a method of its own accepting a upickle JSON AST.

**Comment by rgbkrk** [comment]
Would there be a decent way to provide a serializer? In Vegas for instance, `plot.toJson` returns the stringified version of the JSON.

**Comment by TaoRuan** [comment]
Sorry to ask. But could you please tell how to use this kernel given that I have install jupyter notebook?

**Comment by alexarchambault** [comment]
@TaoRuan See the instructions at https://github.com/alexarchambault/jupyter-scala.

The issue here is fixed (featured in jupyter-scala >= `0.4.0`).

**Comment by TaoRuan** [comment]
@alexarchambault 
Thanks. However I am trying to use it on Windows. It seems not to support Windows 10, right?
I just cannot directly run jupyter-scala script, no matter what environment I am in, the CMD or ubuntu subsystem
